<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Meziantou.Analyzer" Version="3.0.292">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.AI" Version="10.10.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.12" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.12" />
		<PackageReference Include="OllamaSharp" Version="5.5.0" />
		<PackageReference Include="Roslynator.Analyzers" Version="5.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
	  <EditorConfigFiles Remove="C:\Workspaces\red-pen\src\redpen.core\.editorconfig" />
	</ItemGroup>
	<ItemGroup>
	  <None Include="C:\Workspaces\red-pen\src\redpen.core\.editorconfig" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\redpen.abstractions\redpen.abstractions.csproj" />
	</ItemGroup>
</Project>
